#!/usr/bin/env bash

# Generated by Spellcaster ☱
# © 2023, Distinguished LLC. All rights reserved.

# Name: createArchVM
# ID: a188b459-99ba-40c8-9b3a-13951d35ec2d
# Description: A spell to switch context from local to a fresh Arch compute instance
# Identity: topherludlow@protonmail.com

exec 3>&1
exec > >(tee -a spellcaster.log) 2>&1

start_time="$(date -u +%s)"
echo -en "\033[0;37m"
cat << "EOF"
 __                        
(_ ._  _ || _ _. __|_ _ ._ 
__)|_)(/_||(_(_|_> |_(/_|  
   |                       
EOF

echo -e "Name: createArchVM"
echo -e "ID: a188b459-99ba-40c8-9b3a-13951d35ec2d"
echo -e "Description: A spell to switch context from local to a fresh Arch compute instance"
echo -e "Identity: topherludlow@protonmail.com"
echo -e "Converging 12 resources..."
converge=''
cycle=0
converged="$(printf "\xE2\x98\xB1%.0s "  $(seq 12))"
echo -en "\033[0m"

while [ "$converge" != "$converged" ] && [ $cycle -le 12 ]
  do
    converge=''
    if (systemctl is-active libvirtd > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 libvirtd should be running"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 libvirtd should be running"
      echo -en "\033[0m"
      u_out=$(sudo systemctl start libvirtd)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (systemctl is-enabled libvirtd > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 libvirtd should be enabled"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 libvirtd should be enabled"
      echo -en "\033[0m"
      u_out=$(sudo systemctl enable libvirtd)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (test -s /var/lib/libvirt/images/${VM:-arch-vm}.qcow2 > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 /var/lib/libvirt/images/${VM:-arch-vm}.qcow2 should exist"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 /var/lib/libvirt/images/${VM:-arch-vm}.qcow2 should exist"
      echo -en "\033[0m"
      u_out=$(sudo qemu-img create -F qcow2 -b /var/lib/libvirt/images/Arch-Linux-x86_64-cloudimg.qcow2 -f qcow2 /var/lib/libvirt/images/${VM:-arch-vm}.qcow2 ${VM_STORAGE:-50G})
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (pacman -Q qemu-base > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 qemu-base should be installed"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 qemu-base should be installed"
      echo -en "\033[0m"
      u_out=$(sudo pacman -S qemu-base)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (virsh list --state-running | grep ${VM:-arch-vm} > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 The VM ${VM:-arch-vm} should exist"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 The VM ${VM:-arch-vm} should exist"
      echo -en "\033[0m"
      u_out=$(sudo virt-install --name ${VM:-arch-vm} --os-variant archlinux --disk path=/var/lib/libvirt/images/${VM:-arch-vm}.qcow2 --cloud-init user-data=./arch-vm_cloud-init --import --noautoconsole)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (test -z "$(checkupdates)" > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 There should be no Arch system updates available"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 There should be no Arch system updates available"
      echo -en "\033[0m"
      u_out=$(sudo pacman -Syu)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (virsh net-info default | grep "Autostart:.*yes" > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Virsh default network autostart should be enabled"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Virsh default network autostart should be enabled"
      echo -en "\033[0m"
      u_out=$(virsh net-autostart default)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (groups $USER | grep libvirt > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 $USER should belong to libvirt group"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 $USER should belong to libvirt group"
      echo -en "\033[0m"
      u_out=$(sudo usermod -aG libvirt $USER)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (test -s /var/lib/libvirt/images/Arch-Linux-x86_64-cloudimg.qcow2 > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Backing image /var/lib/libvirt/images/Arch-Linux-x86_64-cloudimg.qcow2 should exist"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Backing image /var/lib/libvirt/images/Arch-Linux-x86_64-cloudimg.qcow2 should exist"
      echo -en "\033[0m"
      u_out=$(sudo wget https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2 -O /var/lib/libvirt/images/Arch-Linux-x86_64-cloudimg.qcow2)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (pacman -Q virt-manager > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 virt-manager should be installed"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 virt-manager should be installed"
      echo -en "\033[0m"
      u_out=$(sudo pacman -S virt-manager)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (pacman -Q libvirt > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 libvirt should be installed"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 libvirt should be installed"
      echo -en "\033[0m"
      u_out=$(sudo pacman -S libvirt)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (virsh net-info default | grep "Active:.*yes" > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Virsh default network should be active"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Virsh default network should be active"
      echo -en "\033[0m"
      u_out=$(virsh net-start default)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    echo -e "cycle $cycle"
    echo -e "$converge"
    echo -e "$converged"
    cycle=$(( cycle+1 ))
done

end_time="$(date -u +%s)"

  echo -en "\033[1;33m"
  echo -e "* The Spellcaster free tier includes up to 10 trigraphs. You are at 12 trigraphs and should sign up for an individual plan here https://spellcaster.sh/pricing.\n"
  echo -en "\033[0m"

if [ "$converge" = "$converged" ]
then
  elapsed="$((end_time-start_time))"
  echo -en "\033[0;37m"
  echo -e "Spellcaster converged in $cycle cycles"
  echo -e "Convergence time: $elapsed seconds"
  (( RANDOM%20 == 0 )) && cat <<-EOF | base64 -d | gzip -dc
H4sIAAAAAAAAA7VX7W7aUAz9z1ODhkpQVyFt09SqanM/ENG0VatGxYfowrvcJ5l9bEMCBAJ0klWF
5N7r4+Nj+za5brrYIplLcQzDz0uP6lyyLZDvWXJ5co/JDc3oeZXCmj8RLP+/cRAIv06u10zSnQGa
tEdzJo6TINiyFIoU+8yQ0tPn9PkyxaIJ2Tk4AsVKID61WHzPK+MclAyZnvgzxTL5v/zyWhwMYmDP
sJ3gai8XWL8CoBIsUgBLxbfHSmscUc7daPPIYtMsuxzYm0rW+CvZl/NxcIEgoLBTq00mrCA7/qaN
i2YcQfy9sdCYVSHj1qq0SaqZLXhA0GuT6oTV2lw+nQbfJRyfTEF7GyosEe8epo7pC745o48p9mot
8rpGWTtEE/oZXjaYBEd8Z9rjnkkKwhJJWelLP4O+yP6A7brx1+/6NZR2Ts6p8SNN1r4jTty8w564
kB7wW3ZSUu5UAZwgaD6s8DdLcYU4ZsoZtQT29NsoNF49tvscrNxb2yD1/EhublERiFtUdS76eDA1
vTBjTABtGzNVbsTFEmYA1NXF7msKE/7KZwlKVDW1S8Khcpak0II+G3eOgs90UB7n5YUXeyG+ptNM
617VhEkWXplSdjOor6SUDVNcWmejiEdonfVSoo0ElJN7g+TOrAJ2+1BD3fIcARNCrITOI8MW+HfE
sarsKgFuui2E6FSMfOCSWWENHG4nh3Bw9eaYTGs8v2tM8Sn5OURAsKbJvSGmKdj+hmdK1jO4HKfw
xjOFw1hoIw+IhOR1qIsc5GMB+WCuksttEENryRXyY3eXqtqyDbUFnkkuT9shdQqHcRBfMZwyvUxw
NJtOQJVCfDxXOuwU4q12HWdK7EFAE+jsrHkrNSwScX3sL9QfFbD44G7xbHEjQWFmwyW3xQstKBGH
F4W2x6Gl6NF/5JR1Ja9H+r1g6qnOWGEe4qDk/lJM5+EglXgMbukNQqnkq3FLNbMFGtQAoi742kBE
XoTD0LBgl5omL81qfBTBWFuqTAPuhGvltdna3D8ye5AakVkzqXTYDQK5qed7IshOerno/wYHIbNg
K/demZenb9Efi0ONBpNchsvtTLnIrsQh9gF3pc4/2V8NtlgOAAA=
EOF
  echo -en "\033[0m"
  exit 0
else
  elapsed="$((end_time-start_time))"
  echo -en "\033[0;37m"
  echo -e "Spellcaster failed to converge in $cycle cycles"
  echo -e "Convergence time: $elapsed seconds"
  echo -en "\033[0m"
  exit 1
fi
